# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 13:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170912_0539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='urladd',
        ),
    ]
