# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_remove_post_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=50)),
                ('contact_surname', models.CharField(max_length=50)),
                ('contact_email', models.EmailField(max_length=100)),
            ],
        ),
    ]
